'''
Created on 04 gen 2019

@author: Lorenzo Guenci (Student ID 1532651)
'''

def countNT (dna):
    DNA=dna.upper()
    A=DNA.count("A")
    C=DNA.count("C")
    G=DNA.count("G")
    T=DNA.count("T")
    if (A+C+G+T) != len(dna):
        print("Something wrong occurred")
    return A, C, G, T
    
        

if __name__ == '__main__':
    dna = "AGCAACCACAGTAGGGTCTCAGTCCTGTTTATAGGTGTTGAGTCTACGGACCGTTATTATCGTCATCGGTCCAATATCAGAGGTCTGTCGGGACGACCTCACTGGGCTTTCGATAATCAAACGCCTAAAGATGGGTCGCTTAGTAAGGAAGTTAGAGTGGTACGCACCACTTCCAAGCTCCTACGCAACCTGACAACTATTATGCAGGGGTAACCATTACATGATTGTCGTCTCCTAATCGAGGCCTGGACCTTTTCTTCGGCATCATGGTTTGTTACTTGGTTAGAGGGAAACGTTTGTTCAAACGGTGGCATTAAAAGAAGAAAGTAGGTTGCGAGAGATATGCCGTTGTCGTCGGCGGGTAGGTACGAACCTTGCCTTGACTCTATTATAATATGGTATTCCAAATTGCTATGCAAGGACGGACGCATTATGCTAGTCATTGAGGAATGGGCAAAACCTTGACCGCGGTTGTACACCTTCTGCGTTAGGCACACTGCACGCGTTGTACGCTCGGTGGAGGTGGACTCAGCGGGGTTGACTTTAGGGGGCATACACGGCTCTACGCGTTAAGTTCTCTAAGGTTCACGCAGGTCGGTATTGAGCAACTTAGGACACGGACTGCTATGGTGACAATCTGGAAGCATGAGAGCTAAACGCGGCTGGCTTCCAGCACATCGGGAAAGTTGGGCATACATCCGACGTCGCGACTCTAGTAAGCGCGCCCCACGCTTCCACTAGAACGTTAGGGCCTAAGGGTTCTTCAATTCCTCTAGATGCTTGTTTACTTCGTCACTCATGACCATGACAAGAGAGTCTCCCATTAAAGTCTCTGGGCCCTGGATTTGGTTCAACGAGTTCCCGGGAATAGACGATAGCGCACTACACACCGGCGGGAACCACTCGAAGTTATTACCCGGGAAATAAGGGGTGCTAGGAATTCATTATCTAATCGTCTCATACTATGGGGAGTGTGCCGGTTCTTAGTATGGTT"
    A,C,G,T = countNT(dna)
    print(A,C,G,T)
