'''
Created on 04 gen 2019

@author: Lorenzo Guenci (Student ID 1532651)
'''
def translatingToProtein (s):
    codon_table= {
        "GCU": "A",
        "GCC": "A",
        "GCA": "A",
        "GCG": "A",
        "CGU": "R",
        "CGC": "R",
        "CGA": "R",
        "CGG": "R",
        "AGA": "R",
        "AGG": "R",
        "AAU": "N",
        "AAC": "N",
        "GAU": "D",
        "GAC": "D",
        "UGU": "C",
        "UGC": "C",
        "CAA": "Q",
        "CAG": "Q",
        "GAA": "E",
        "GAG": "E",
        "GGU": "G",
        "GGC": "G",
        "GGA": "G",
        "GGG": "G",
        "CAU": "H",
        "CAC": "H",
        "AUU": "I",
        "AUC": "I",
        "AUA": "I",
        "AUG": "" ,
        "UUA": "L",
        "UUG": "L",
        "CUU": "L",
        "CUC": "L",
        "CUA": "L",
        "CUG": "L",
        "AAA": "K",
        "AAG": "K",
        "AUG": "M",
        "UUU": "F",
        "UUC": "F",
        "CCU": "P",
        "CCC": "P",
        "CCA": "P",
        "CCG": "P",
        "UCU": "S",
        "UCC": "S",
        "UCA": "S",
        "UCG": "S",
        "AGU": "S",
        "AGC": "S",
        "ACU": "T",
        "ACC": "T",
        "ACA": "T",
        "ACG": "T",
        "UGG": "W",
        "UAU": "Y",
        "UAC": "Y",
        "GUU": "V",
        "GUC": "V",
        "GUA": "V",
        "GUG": "V",
        "UAG": "",
        "UGA": "",
        "UAA": "",        
        }
    protein=""
    for i in range(0,(len(s)//3)):
        protein+=codon_table.get(s[(i*3):(i*3)+3])
    return protein
if __name__ == '__main__':
    s="AUGUCUUCUCUAUUGAGCUGGACCUUAUAUUCUAUUCACUUCCUAGCAAUUGUAGGCGUAACUCCAGAAAACCUGAACCAUCUUUUGGGUGAUGUUAGGA"
    s+="UAGCCGAGUGGACACUGUCUUUGGCUUUACAGGGGGUGAAACCUAUAAUUCAACACCCCCUGGUAGGGACACAGAACCCGCAGUUACCUAAAGUCUGUCU"
    s+="UGCUCAAGCAUGCCUAUUUCUGGUUACAGGCGCCAACUUUGACGGACACCAUCACAUCGCGCGUACGCCCAUCGUCCCGGAAUCACCGAUUAUACUUUCC"
    s+="CUUGAGUCGCACCGCAGCUGUUGGCCUGUCUAUCUUGGUACGCUUGCUAUACCCCCACGUUCCGGCAGAAGUGAUGAGCUGUCCAUCUACCGUCUUACCA"
    s+="UUAACAGUAGUGUAUCGAAAGCAGCCGGUGCCGCUGUGAUGGUGGUCCACGCUCGCUAUUUGCGUUCUCUCGUAUCAGCCCACGCGCUGUCGCCCGGAGG"
    s+="AUGCGUUGCCAUGAUAGACGAUAAGGCCGGUGGAGGGAGGACGGCGCCGCUGAUAGAAGUAGAGCGCGAACUCACCGGGGUCAACGAUGGGCUCCCCCCG"
    s+="GCCUGUCCAAGUGAAAUGCACCUCCACACGAGGAUUAGGGUAUCUCCCACGGACAGCAUCGUCGCAUCUAACCGGACGAUUGCACAAGCGAGCGUACAGG"
    s+="CUAGGAUUCGGUUCUCAUGGAGUCCUAUCUCUCGCAAGCGUCAAAUUACGGUAACGUACAUCCGACGUGGCGUAGAAGUGCAUGUGGGUCUCGUUACUUA"
    s+="UGAGUAUGUAGAGCCAUGGUAUAGCUUUUAUCCGCCUUCAAAUGGCUCUACCCGGGACAAUCAGCGGCCUCUCUUUAGCCCUAAGCUGGUCUCUGUGAUA"
    s+="UAUUGUUCGUGUAUGCAAACUCGUCUGUUCCCUACAAGGAAGCCACUCUUAAGCGGCAGUCACUGGCAAGCAGCUGUUGGGUGCCUCCCCCGCACUCUGG"
    s+="GUCGCAGUGUUUCACGACAUACACAGGGAGCCGGCCCCAGUGCACCAAGGGAUGAGGUUGUGCAGAUAUUCCUAUCAUGUGGAAUAGUCUCGGCUCUUCG"
    s+="GCGCGGUCACCUGACAGUAUGGGGGUCGGAUGUCAAAGAACAUUACAGUCCGGGCUGUUGCGCAACGCCAAUGAGAGCAGGCAGAGAGGUACGCGCUUGC"
    s+="GUGACUCUACUAGGAAUCCAGUGUAUACCUGUCGGUCUUGACGCAUCUCAAUGGCUCAUUACUCCGGUGUUCCUUCUCUCUUCUCCCGAGGCUUUGAUCG"
    s+="AAAGCGCCAGGGGUUCCUAUUCUGGCCGCUUACUGCUACUCUACGGGAGCUUACUAGGAAUUAUGUGGUUAGCAUGGAUCCACAGUUCGAUUAACCCAAU"
    s+="UGUGCGUGACGAGUCCAAGAAGACUAGUAGAGCCACGUCACAACGGCUGUGCUAUAAUGAAACACGGCUACUUUCCACCAACUCGUCCACCUUUUUAGUG"
    s+="UUCUAUCCACUAAGAGCUCCGGCUGUUCCACGGAAAUCGGAAACUGUAGUUAGUGAGGGGAACAGACGAAUCGGGUAUUGUUCGUUGCAUGCUGUCUCCA"
    s+="ACGUGGAUACGAAUGAAAUGCGACCCAACGCCGUUCACCUCCCACAACUACCAACUACUCCAGCACGGCCCGUAUCAGUCGUUGAAGCACCACUAAAGUU"
    s+="UGAACAAGUCUCUUCACUCACAAAUGAGUUUUCUCAGAGGACUAUUCCAUCCGGGAAUACGCGUUACUUGAGAGAGAGUUCGCAGCAUGUCCGGGUAGGG"
    s+="ACACGUGUUGUGGGUGAACCCACAAUAUCGUACAGGUGUCCACCAAACCCGCUAACAAGUUGCGUUGUACAGAAAAUGCAAGGGCGCCACUUUUUAAUGC"
    s+="UCUCGGCCAGAAUGAGUUGGUAUCAGGAGCCGUUCUCUGUUCAAAUGUCUACCGUCAGCGCGUACGCAUGCCACUCUCAUGAGCUUGAAAAACGAGACGU"
    s+="GAGCGUAGGUUGGUUUUGGGAACAAAUCACCGUAAGAAAAAGCGGAGCAGCAUGCCCACAACGCGCCAGUAAGACCUGGAGAUCUGAAGCAGUUCACGUA"
    s+="CGCUCACCACGCGCCAUUUGCCAGUUAUAUCAUCUACGCGGCGUAAGCAGCAACACGAUACAAAUCAGCUCUCAAACGUUCUCGACGGAUCUAAGGCAUC"
    s+="CACCCUCUUUCUUGUUUAGUCGGCUUAGGUGCAAUGACACGCCCUAUUCGUUGCCUACUGUGCUCAUUCCCUCGACUUGUGUCCUCCCUAGGAAUAAGCG"
    s+="GACUAUUGAAGCUGAGAUGUUUGGCGACGCAGGCUCCUCGCUAGCAGAUUCACUUAUUAACGUUGUUAGAGCAAUUUGUAAGAGAUAUCACUUUCCCUUC"
    s+="CGGUACAAGGGACACCGGGGGGUCAAUUUUGGCAGGAGGAGUUUUCUUUUUUCCCCCGCUGGCACCUGUGCCUAUCGUCUGCCACAUGUAUCAUCCGUGC"
    s+="UAAGGUAUAGGAGACGGGCGCCUGACUCCAUACAGGCUUUGCCAAGCCUCCGGUCAGAGAAUUGGCGCUUCCUGACCCUACUGGCAAACCAACGAUUUCC"
    s+="GGUAAGGUUAAGUAUGGGCGAUUGCAUAUAUAAUUAUAUCAUGUCUGGAGCGCCGGGAUGGGCGCACGUAUUCAGUUUUCAGACCGAGGUGUCUUGGGGC"
    s+="UCAUCCCUUCCCCCUCUCCAUGUGUUUCCUUCAAUAAAACAUUUACGCAACUCACCGACUCACCUCUAUUCCUGCCUACAAGUAAUACGAGAUAGAAAAA"
    s+="AGUUCGCAAAGAAGACACCUUCUCACGAAUCGUUACGGGGGCACUCUACCGUCCUACUUCGAUUUAGGAGCUUUUGUUGGUUACACCACAUGAGAAGGCU"
    s+="AGGAGGUGUACCUCAGCCAUAUCCCCCGAGUCUAAUCCUACACGUGAUUUUUAUUCGUCCCGGCAGGCCUGGAGCGGGGAAGAAUAUAGGGAGGAUAUAU"
    s+="GCACAGUUGAAUUCAUUGUACUUUGUAGGAAUUUUCUACCAGUCUCGCUUGCGAAUCUUUAACAGACCUUCUAGGAAACCUUUUAAUUCUGCUAGAUCGG"
    s+="CGUACUCAAUGAAUAGCCCGGACCUAACUCAUAGUUCACCUACAGGGAACCGCAAAUUUGACGACAUUCUCAAGACUUUUGCAGUUCCAUUGUACCGAAG"
    s+="AACGCGGGAGACGGCUCAGCGAUUUCCUCUCUCGAUAGCGGCAGGUUGUUGGCAACCGAGGAGGCUGAUAGAUAACUGCAGGGUAAGGUGUGGGCUGGCG"
    s+="UGUCCCCUCGCGAAGGGAAGCCACCAACCCAGAAGCUGCCAGACACCAUUCCAAAUCGGGUUACUUGUUUCUCAUCUUCUACUAAGCUAUAUGGGGCAUU"
    s+="CGAUUGUAAUUCCCGGAGGACUGAUUGCGACGUGGACCGAAAUGAUGUCAUUUUACCACAAGAGUGAAUGGGCCUCACUCCUCGACUUCAUGCUUUCGUG"
    s+="UGCUCAGCCAGUUCAAGGUCUCGACGCGUCUAAAUCCGGACUCUGCUACACGCUGUCCGGUUGCUGCCUACCACCACGUUCUACCUCCGACACGUGCCCA"
    s+="UACGCUCCCAGGAAAGGUACCGAUCACAGACCCCCGCUAAUAUACAGAUUCCACAAGCUAAGGGUUUAUUGGCAAGGGAGUUUACGAUCUUUAUUAAACG"
    s+="AAUCCGCACUAACUAUCACUCCCAAACCCGCCGCCUCGAAACCUUCGAGCGUCCUAGUGAGAUGGUGUCCAUACAGGCACAACGGCUUCAACGUACGUAG"
    s+="UCUCCAUGAGCGAUAUACUUGUCCUAACAACCUCUAUCCAAGACGGACUCAAUCCUCAAUGCAUCAGCAUGCCUUGCUCAGACUCCAUAUUCAACCGUUC"
    s+="AUAUCCUUUCUCAGUCGAGGUAGUUUCCGCAAAAAGUGUUGCUCGAUGUGCCCAUCAUCCUUAGCCGUACGUGGGGGGCAUGCCCAGCAUUGUUCGCAUC"
    s+="CGCUAAAGCGUUAUAGGCACUACCUAGUCUGCAAGUGCGAAAGACGUCGAAUUAGGGAACUCGCUUCUGCUCUGACGGUAAUAUCCUUUCACAUAUUAUU"
    s+="GUUGGGCGUAGUUGUGCAUCACGGCGCGUCUCCUAGCCUCCGACAUGCUUUUACUUACCGUACACACACAGCAUUCCACCUAAUCCGCAAUACAACAGUG"
    s+="CUCUUGAAGCAGUAUCCUAGUCGAUCUAAGGCCCGGCUAUCUGAGUCAUCGUACUCGUCGACAGAUAAGGAGUGUUUUAUCUUCCGGAGCAAGGAGACGG"
    s+="ACCUUUUUGAUGGAAGGAUUUGUUCUAUAAACGUCCCAGGCUGCGUUUGUCCAGUUGAUGGAUCUCUGACGUUUAUCCUGAUAUUCGUUAGCACCCGAUG"
    s+="UUUUUACCGUUUUCCGGAAGCUGGAUGUAUCCUUUCCGACCAGAUUGGAUUCAGGAUUGGGACGGAUUCACAUAGUGACCAAAGGUGGCGGGCAGAGCAA"
    s+="GCGAGAAAAGUCGCGAACGCUGUACCAAAGUUUUAUCUCAGAGUACUCUCUCUUCGUGUUGCAAGGUCACACCCAGCCCAACGUGGUGAGCGGACUGACU"
    s+="UAGCCUUGGACUAUGGGUCCAUUUUUGAAAUAUCCCCGUGCACCUUAAGUCUUAUCCCAGAGCUUUCACCCGAACACACGGACGGGACAAAGGAGAUGAG"
    s+="UCGCCCCUUUCGCGUCAAAGGCAGCGUGCUAAUGAAGUGUUUAGUAGACGCGUGCAUUACGGGAAAUACUACGGCAGCGGGACGUCCUUUCAAGCGAAGG"
    s+="CGCACUAAAUCUCGAGAUUUAGCCCACCAAGUAGACAUAAUCAUAUUCACAUCUAGAUUCCUAAGUAGUACCUGCGCGAAAGUCGGGGCUAAGGUGGCAU"
    s+="ACGUGCAUGGAGAUAACAAACAACAUACCAGAUACAGAACAUGCACCGAGCGCAACAGAGUAAGCCUGAUGAUUGGCCGUCACGCAAUCGGGCAUAUUGA"
    s+="CAAGCUGAAGAAUUUAAGACAAGUGCCCUUUUGGCCGGUAUUGGCCCAACAGCUUUACGCCCUGAGCGUUGUCGCACAAAACAAGCUUUGUACUAGCCCC"
    s+="GUCCGCAUGGAAACUGUCCCAAGAAGACGUGAGUUGAUGGCCGUUUGUUCGGUCCGUACACGGGAAAGACGCCUGGGCCGCGCAGGCCAGCAUAUAGAUG"
    s+="CCACAGCCAGGACUCAGACCGUAACACAGCACGCUCCAAAAAGCCUUUCUCAAAGACUGCAGAGUCAUAGUGAUAUUUUAGGCACUCGAGGAAAGUCCAC"
    s+="AUUCCUCCGGCAGCUCCAGGCGCAGAACACGAAUGCUAUUGGGGACUGUGUGCGCUCCUUUGCAGUCAGCCAUAGGACAGAUGCACGCGCGAAAUUGCAA"
    s+="CCCGAGAUAUCCACCCUCCACACGGGCAGAGUGGAGGACGGUCUACGAACCGCCGUACCCCCUUCCGGGUCAUCACGGGAUUCGCGCAUCGGCGCCGUGC"
    s+="GAUUCCAGACUGUCUCGUUGAGAUCUAAAGGAAUUUCUCAAAGUAAAAUCAAGGACUUUAUACUAUCGCGGUAUUUUUUUAUCAGAACCCUCGGAACGGU"
    s+="ACUUUUCUUUCCUCUACUCCGCGUACGAGGACGCCCACCUACGUCUAUCAGUACUCUCGUCCCGUACAAAAGGCCUAAGUUUAGAGGACGGGCUGCUGAG"
    s+="AAACAAAGACGAUCGAGCGUGAUAUACAGUAGUGUCACAACGUGGUCGGGGUCUCAUUCCGCCCACUACUUUGAUUCAGACCGUAGACUUAACAACCCAA"
    s+="UUAGCUUACUCGUCACCCCAAUAACCACCCCUCCAGAGUUUUCCAGUUUCGCAUCAUCUGCUGAGACGCGUAAUUUUUUGCACUCGUCGUUCUUCGUCCC"
    s+="UGACAGUGACACAUCGGAAUAUGUAUGGAUGGGGGCCUGCCGGUCAACGCAAUUACAUAAGGUGAAGUUGGAUUUGUCGCUUCCCCAGGAGGGCCGCUUC"
    s+="AAUGCUUUGAGAAGUAGACCUCCAUUCGUAAUCAUGCCCCGGCAGGCUAACUUGCGAAAGUGGUCUCUGCAAAUUCCUGCCUAUCCGGGUUACACGGGAU"
    s+="CUAGAAGCUCUGGCUCUAACCACUAUGCUCAGCUGACGUUUGGAUCCAUAGCAUUGUCAAUACGCACGGCGAAUUCGGGUCGGUCAGCACGGUGGAUACC"
    s+="CACCGAAACAGCGGCGAUAGUGCUAUCCCUGACGCAUUCGAUGGCUCCACCGUAUCUAGGCUGCCGAAGGAUUGCCUAUCCCGAAUACAUGAUCUCGCCG"
    s+="AACUUGACUAGCUGUGCAGCGUAUAGUACUAACAUGCGGGCCCAUGAUGUCAUAGGGGCAUCGACGGCCAACAUAUGCAAAAAACCUCCUAGCAUCUGUA"
    s+="CCGUCGGAUAUCUGCGUACAUCGGACGCGCUUCGAUUCUGGUCGGGAUGCGACGAUUCCUUCUCAUGUUACAUGACUUUAAAACGGUUACGCUUUCGCCA"
    s+="GACAAACCGUCACCGCAAUGAAAGGAUCCGGGGUGUGCAACCAGCGACGCCCCAGCGUCCCGGUGCAUCCUUAAAUGAGAGAUGCCGGUCCAGGAGGGGC"
    s+="CAACUGUGGAUCGAGACGCCCGGACCGCGAUACUUUUUACGACGUGUACCUGCUAAGGUUGACCAUGGUAGUCGGCAGCGUCUACGUGUGACGCGACACU"
    s+="ACGGUCUAGUCGCUGCCAACAUGAGUUUAAAGAGCUGGGUUUCAGAAAGGGCGGUGAGGCUUAGCCGUUGGAUUGAUAGGAAGAGAACACACACUGCUUU"
    s+="GCUCGAUGGGGUGUAUCACACGGGGCAAAGAAUGGGCGGAAAUGUUUGCAUAUUUUUGGGCUACACGCGCACAUCCGUGCCACUUAAGGGCAUACCGACG"
    s+="AGCACGUGUCCAAAGGGCGCCUCGCAUCGUUACGCAUUCCGCACUCCAGAGACCACAAGGCUUAUCAGCAGAAGUCUUCGGCAUUCUACUGGGUUAACGG"
    s+="UAAUCAGUGCCAAUCAUUUGCGGACCAAUCUGUGUAGUAAGCGUACCGAGUCACUCCAGUUAGAACGGGCCCACGAUUCAGUCAACCCCGAGUGGCGCUU"
    s+="UCGGCCCGAUAUCUUGUGCCGGCCGUCAUCGCACGUGACCGCCCGCGGUGUGUCCUUCUAUACCUCCCUGCAGCUUCGUUUCGCCCAACCCAAGAGACAA"
    s+="GAAGGAGUGGUAACCGUGUGUCGAGCGCCGGAUUUAUUGAUUUGGCUCCUAUUAUGCUGCGCCUCCAAGGUAACCUGUUUGUAUGUGCAGAUGACCUGUA"
    s+="ACCCGGGUCAAUACGUCUCUCAUUGCUUCCAUAAACUGGUGGCGCUGCCGAUUACUUCUAUAGUCGGCGUGCGGAUCCCAUAUUUCUAUCGUCGACGCCG"
    s+="GCACGUGAAGUCGUCGUUGAGAGCGACUAGCAAUUUCUUAACGAGCACCAGGUAUUUACACAGCAGCCUCCAACUUUAUACGAUGGCUAUGUCAGAAUGU"
    s+="CCGGUGACUCAAGUAGUUUCAGUUAAAAAUGCUCCCAUUAUAUGCAUUUUGAGAGAAGUACAAACAUUUCCUUGUUCGUCGGUUCAGUCUCAUCACCCAA"
    s+="CCUGGGAUUGUUGUGGAACGACUGUUGUUCGCAAGCUCGCGGUCUACAUGCCAGUAUCAUGGCUUCCGCGGUCAGCCAUACUUUUAGACGGUGCGACAUG"
    s+="UAAAUUCGAAUUUUUCCCCGAUGAUAAUAAGCCACAGUUGCUUAGUCCGAAUACGAAUGAAGACCGAGCCCUCGCCUGCUCCUGUCAAUCGCGAUACAAU"
    s+="AGUACUGAAGCUACACUUAUAUCGAACACGACGCGGCGCUCCAACGGGUUGACAAAUGCGGGGGCAGGUCGAAGGAUACCAAGCUUGAGUGGAUGUCCAG"
    s+="GUGAAUCCACAUUAGACAGAGGCAAUGCAACUUCAGCGGAUAAGCGCACCGGACGAGCUCUCACCAUUGGUGAAGCGAUCAUACCCCAGUGGUGCUUUUC"
    s+="CUCUAUUUAG"                                                                                          
    print(translatingToProtein(s))