'''
Created on 04 gen 2019

@author: Lorenzo Guenci (Student ID 1532651)
'''
def reverseComplement(dna):
    revdna=""
    #definition of the base pairs complements
    switcher = {
        "A": "T",
        "T": "A",
        "C": "G",
        "G": "C",
    }
    #inspect the dna string in reversed order and switching the nucleotide to its complement
    for nt in dna[::-1]:
        revdna+=switcher.get(nt)
    return revdna
if __name__ == '__main__':
    dna="TGCCGACAACAAGAGGGTTCCTGAGCTCTGTAGGTTTAACGAGATGCGATTAGGAATCAATAGTTGCTGCTCCTCAAGCGATCGCACCTTAATTCGCACGACGGAACTCTGAGGAATATGTGAACTAAGACCCGCAATAGGGGTACAAGTCGTGGGCCCGACGCTGGACCCAGATAGAACCGCTAAGCCCCTTGGCACGATTACTGCTGCTTTCGTCTTGCATTGGACATCTGTAGCTTTCTCGGAGCAGCAGTTCGTGCGTACGAGTGCATACGCGCCTATAGCAATCCATCCGACTGCGAAGGGACATGGAAAAGGCCTTCGGTATAACACGTACCCCACTAGAGAGCGCCCGTATAGTTCGCGCACGGCGTGCGTTTATGTTGTGGTCGCTAGCATACTGTCTGAAAGCGTTGCAATTTCAGGGCGGGCACCATTCCTTTAGCCAATCGGGCCAGCTGCCCAATGCTGGCTTATCCCTAGCTAGTTCGTAGCAACCATCCAGTGAACAGTCTTCAAGCTCGCATACCGGGGCCTTGATCTTTACAAACCATTTCGGTTTGATAACAACGTATGTGACCAAGATCAAACTACTCATTTCACAATTGCGTTGCGACAACCCGTCATTATCTATGACACGATAGGCTAGACCCTCTACTTGATACGGCGGCGCGATACAATACGTCTGAACGGTCGTGGCTATTAATGTCATTTTTACATCGGGTCTGACTCGTTAGTATCTTATAATCAGCCTAATGTGAACGTGTAACACTTCATCAAATACAATTATCGTAGAGCTTGCAGTCCGCCTATAACCTGAGATCCCGGAGGCGAATAAAACCTCTATTATAACGAGTTCATTCCATACAACGGCCGTATATAGACCCGCTTCTGCCCTTTACGCACTGAACCCTAGAACGTTATTTACTTGGTATTCCTTACCTATCTATGCGTTGTATAGAATCTCG"
    print(reverseComplement(dna))